# Generated by Django 4.2.4 on 2023-08-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_citymst'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymst',
            name='Name',
            field=models.CharField(default='a', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citymst',
            name='State',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.statemst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citymst',
            name='StateCode',
            field=models.CharField(default='24', max_length=5),
        ),
    ]
