# Generated by Django 4.2.4 on 2023-08-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_citymst_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymst',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.statemst'),
        ),
    ]
