# Generated by Django 4.2.4 on 2023-08-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_alter_citymst_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Other1', models.CharField(blank=True, max_length=60)),
                ('Other2', models.CharField(blank=True, max_length=60)),
                ('CrDtTm', models.DateTimeField(auto_now_add=True)),
                ('CrBy', models.CharField(blank=True, max_length=60)),
                ('CrFrom', models.CharField(blank=True, max_length=60)),
                ('UpdDtTm', models.DateTimeField(auto_now=True)),
                ('UpdBy', models.CharField(blank=True, max_length=60)),
                ('UpdFrom', models.CharField(blank=True, max_length=60)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.citymst')),
            ],
            options={
                'verbose_name': 'CityArea',
                'db_table': 'CityArea',
            },
        ),
        migrations.AddConstraint(
            model_name='cityarea',
            constraint=models.UniqueConstraint(fields=('City', 'Name'), name='unq_CityName_CityArea'),
        ),
    ]
