# Generated by Django 4.2.4 on 2023-08-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_custgrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Other1', models.CharField(blank=True, max_length=60)),
                ('Other2', models.CharField(blank=True, max_length=60)),
                ('CrDtTm', models.DateTimeField(auto_now_add=True)),
                ('CrBy', models.CharField(blank=True, max_length=60)),
                ('CrFrom', models.CharField(blank=True, max_length=60)),
                ('UpdDtTm', models.DateTimeField(auto_now=True)),
                ('UpdBy', models.CharField(blank=True, max_length=60)),
                ('UpdFrom', models.CharField(blank=True, max_length=60)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.citymst')),
                ('CityArea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.cityarea')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.statemst')),
            ],
            options={
                'verbose_name': 'CustAddress',
                'db_table': 'CustAddress',
            },
        ),
    ]
