# Generated by Django 4.2.4 on 2023-08-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_tagmst_custtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='custtag',
            name='Tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Dashboard.tagmst'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custtag',
            name='TagCode',
            field=models.CharField(max_length=5),
        ),
    ]
