# Generated by Django 4.2.4 on 2023-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_groupmst'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmst',
            constraint=models.UniqueConstraint(fields=('Code', 'Name'), name='unq_Code_GroupName'),
        ),
        migrations.AddConstraint(
            model_name='tagmst',
            constraint=models.UniqueConstraint(fields=('Code', 'Name'), name='unq_Code_TagName'),
        ),
    ]
