# Generated by Django 4.2.4 on 2023-08-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_groupmst_unq_code_groupname_tagmst_unq_code_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmst',
            name='Code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmst',
            name='Name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmst',
            name='Code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmst',
            name='Name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.DeleteModel(
            name='CustTag',
        ),
    ]
