# Generated by Django 4.2.4 on 2023-08-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_alter_groupmst_code_alter_groupmst_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmst',
            name='unq_Code_GroupName',
        ),
        migrations.RemoveConstraint(
            model_name='tagmst',
            name='unq_Code_TagName',
        ),
    ]
