# Generated by Django 4.2.4 on 2023-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_custmst'),
    ]

    operations = [
        migrations.AddField(
            model_name='custmst',
            name='DealerTyp',
            field=models.CharField(choices=[('1', 'Regular'), ('2', 'Unregistered'), ('3', 'Composition')], default='2', max_length=20),
            preserve_default=False,
        ),
    ]
