# Generated by Django 4.2.4 on 2023-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_custmst_dealertyp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custmst',
            options={'verbose_name': 'CustMst'},
        ),
        migrations.AlterField(
            model_name='custmst',
            name='DealerTyp',
            field=models.CharField(choices=[('1', 'Regular'), ('2', 'Unregistered'), ('3', 'Composition')], default='2', max_length=10),
        ),
        migrations.AlterModelTable(
            name='custmst',
            table='CustMst',
        ),
    ]
