# Generated by Django 4.2.4 on 2023-08-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_alter_custmst_options_alter_custmst_dealertyp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custmst',
            name='ContPrsnEMail',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='custmst',
            name='OthContPrsnEMail',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='GrpMstCode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthCityAreaID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custmst_othcityarea', to='Dashboard.cityarea'),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthCityMstID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custmst_othcitymst', to='Dashboard.citymst'),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthCountry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthStateCode',
            field=models.CharField(blank=True, default=24, max_length=5),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthStateMstID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custmst_othstatemst', to='Dashboard.statemst'),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='StateCode',
            field=models.CharField(default=24, max_length=5),
        ),
    ]
