# Generated by Django 4.2.4 on 2023-08-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_custmst_contprsnemail_custmst_othcontprsnemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmst',
            name='OthCityAreaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custmst_othcityarea', to='Dashboard.cityarea'),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthCityMstID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custmst_othcitymst', to='Dashboard.citymst'),
        ),
        migrations.AlterField(
            model_name='custmst',
            name='OthStateMstID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custmst_othstatemst', to='Dashboard.statemst'),
        ),
    ]
