# Generated by Django 4.2.4 on 2023-08-17 04:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_userprofile_userloginprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistrationProfile',
            new_name='Staff',
        ),
        migrations.RenameModel(
            old_name='UserLoginProfile',
            new_name='UserLogin',
        ),
    ]
