# Generated by Django 4.2.4 on 2023-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_userregistrationprofile_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user_type',
            field=models.CharField(default='superuser', max_length=50),
        ),
    ]
