# Generated by Django 4.2.4 on 2023-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staff_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='random_password',
            field=models.CharField(default='default', max_length=8),
        ),
    ]
