# Generated by Django 4.2.4 on 2023-08-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staff_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='city',
        ),
    ]
