# Generated by Django 4.2.4 on 2023-08-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_staff_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(default='sup', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
