# Generated by Django 4.2.4 on 2023-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staff_crby_staff_crfrom_staff_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ForceReset',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='isActive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
