# Generated by Django 4.2.4 on 2023-08-21 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_staff_crdttm_alter_staff_upddttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CrDtTm',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 9, 39, 1, 60538)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdDtTm',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 9, 39, 1, 61537)),
        ),
    ]
