# Generated by Django 4.2.4 on 2023-08-21 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_staff_crdttm_alter_staff_upddttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CrDtTm',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 11, 59, 10, 376349)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdDtTm',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
