# Generated by Django 4.2.4 on 2023-08-21 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_staff_crdttm_alter_staff_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CrBy',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='CrDtTm',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 12, 7, 50, 804504)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='CrFrom',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Other1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Other2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdBy',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdDtTm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdFrom',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
