# Generated by Django 4.2.4 on 2023-08-21 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_staff_crby_alter_staff_crdttm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CrBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='CrDtTm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 10, 7, 168117), null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='CrFrom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Other1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Other2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdDtTm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdFrom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
