# Generated by Django 4.2.4 on 2023-08-21 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_staff_crby_alter_staff_crdttm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CrDtTm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 19, 7, 108297), null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdBy',
            field=models.CharField(blank=True, default='abc', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdDtTm',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdFrom',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
