# Generated by Django 4.2.4 on 2023-08-23 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_alter_staff_crby_alter_staff_crdttm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CrBy',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='CrDtTm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='CrFrom',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ForceReset',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Other1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Other2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdBy',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdDtTm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='UpdFrom',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
