# Generated by Django 4.2.4 on 2023-08-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_staff_crby_alter_staff_crdttm_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
    ]
